name: k6 Load Tests

on:
  push:
    branches:
      - github_actions


jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем необходимые зависимости
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates gnupg curl

      # Шаг 3: Добавляем GPG-ключ и репозиторий k6
      - name: Add k6 repository
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://dl.k6.io/keys/gpg-keyring.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/etc/apt/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update

      # Шаг 4: Устанавливаем k6
      - name: Install k6
        run: sudo apt-get install -y k6

      # Шаг 5: Запускаем нагрузочные тесты
      - name: Run k6 tests
        run: k6 run scripts/load-test.js