name: k6 Load Tests

on:
  push:
    branches:
      - github_actions

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Шаг 3: Устанавливаем k6 локально
      - name: Install k6
        run: npm install k6

      # Шаг 4: Запускаем нагрузочные тесты через npx
      - name: Run k6 tests
        run: npx k6 run scripts/load-test.js